### ISSUE TITLE
Cannot type

### ISSUE THREAD

**Issue by LeanderVanBaekel** [pomdtr/tweety#11]
Hi! 
After installing I and clicking on the extension I only see a blinking cursor and cannot type anything in the tab. 

I used the command:
wesh init --browser chrome --extension-id <id>

I also tried:
wesh init --browser arc --extension-id <id>
because i'm using Arc.

I see this error in the extension log:
Unchecked runtime.lastError: Specified native messaging host not found.
Context
Unknown
Stack Trace
:0 (anonymous function)

Do you have any ideas?

**Comment by pomdtr** [comment]
Can you retry with latest release ? I use arc myself, it should work now.
