### ISSUE TITLE
Specify fonts

### ISSUE THREAD

**Issue by 5ouma** [pomdtr/tweety#13]
I want to specify fonts to show Nerd Fonts on my terminal prompt.
If I can set multiple fonts, it's great!

**Comment by pomdtr** [comment]
Great suggestion. I plan to add support for all xterm.js features in the config in the next release.

**Comment by pomdtr** [comment]
Fixed in 0.8.0. Added a new `xterm` property that you can use to pass any field from [ITerminalOptions](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/).
